// Language code to name mapping
export const getLanguageName = (code: string): string => {
  const languageMap: { [key: string]: string } = {
    'en': 'English',
    'zh': 'Chinese',
    'ja': 'Japanese',
    'ko': 'Korean',
    'es': 'Spanish',
    'fr': 'French',
    'de': 'German',
    'it': 'Italian',
    'pt': 'Portuguese',
    'ru': 'Russian',
    'ar': 'Arabic',
    'hi': 'Hindi',
    'bn': 'Bengali',
    'th': 'Thai',
    'vi': 'Vietnamese',
    'id': 'Indonesian',
    'ms': 'Malay',
    'tr': 'Turkish',
    'pl': 'Polish',
    'nl': 'Dutch',
    'sv': 'Swedish',
    'da': 'Danish',
    'no': 'Norwegian',
    'fi': 'Finnish',
    'cs': 'Czech',
    'sk': 'Slovak',
    'hu': 'Hungarian',
    'ro': 'Romanian',
    'bg': 'Bulgarian',
    'hr': 'Croatian',
    'sr': 'Serbian',
    'sl': 'Slovenian',
    'et': 'Estonian',
    'lv': 'Latvian',
    'lt': 'Lithuanian',
    'el': 'Greek',
    'he': 'Hebrew',
    'fa': 'Persian',
    'ur': 'Urdu',
    'ta': 'Tamil',
    'te': 'Telugu',
    'kn': 'Kannada',
    'ml': 'Malayalam',
    'gu': 'Gujarati',
    'pa': 'Punjabi',
    'mr': 'Marathi',
    'ne': 'Nepali',
    'si': 'Sinhala',
    'my': 'Burmese',
    'km': 'Khmer',
    'lo': 'Lao',
    'mn': 'Mongolian',
    'ka': 'Georgian',
    'hy': 'Armenian',
    'az': 'Azerbaijani',
    'kk': 'Kazakh',
    'ky': 'Kyrgyz',
    'uz': 'Uzbek',
    'tk': 'Turkmen',
    'tg': 'Tajik',
    'ps': 'Pashto',
    'sd': 'Sindhi',
    'bo': 'Tibetan',
    'ug': 'Uyghur',
    'yi': 'Yiddish',
    'cy': 'Welsh',
    'ga': 'Irish',
    'mt': 'Maltese',
    'eu': 'Basque',
    'ca': 'Catalan',
    'gl': 'Galician',
    'is': 'Icelandic',
    'fo': 'Faroese',
    'sq': 'Albanian',
    'mk': 'Macedonian',
    'bs': 'Bosnian',
    'me': 'Montenegrin',
    'af': 'Afrikaans',
    'zu': 'Zulu',
    'xh': 'Xhosa',
    'st': 'Southern Sotho',
    'tn': 'Tswana',
    'sw': 'Swahili',
    'am': 'Amharic',
    'ti': 'Tigrinya',
    'so': 'Somali',
    'ha': 'Hausa',
    'yo': 'Yoruba',
    'ig': 'Igbo',
    'ff': 'Fula',
    'wo': 'Wolof',
    'sn': 'Shona',
    'rw': 'Kinyarwanda',
    'ak': 'Akan',
    'tw': 'Twi',
    'ee': 'Ewe',
    'lg': 'Ganda',
    'ny': 'Nyanja',
    'bem': 'Bemba',
    'loz': 'Lozi',
    'to': 'Tongan',
    'fj': 'Fijian',
    'sm': 'Samoan',
    'haw': 'Hawaiian',
    'mi': 'Māori',
    'qu': 'Quechua',
    'ay': 'Aymara',
    'gn': 'Guarani',
    'ht': 'Haitian Creole',
    'jv': 'Javanese',
    'su': 'Sundanese',
    'ceb': 'Cebuano',
    'tl': 'Tagalog',
    'fil': 'Filipino',
    'mg': 'Malagasy',
    'co': 'Corsican',
    'br': 'Breton',
    'lb': 'Luxembourgish',
    'fur': 'Friulian',
    'rm': 'Romansh',
    'lad': 'Ladino',
    'sc': 'Sardinian',
    'vec': 'Venetian',
    'nap': 'Neapolitan',
    'scn': 'Sicilian',
    'pms': 'Piedmontese',
    'lmo': 'Lombard',
    'eml': 'Emilian-Romagnol',
    'lij': 'Ligurian',
    'pcd': 'Picard',
    'wa': 'Walloon',
    'frp': 'Franco-Provençal',
    'oc': 'Occitan',
    'gsw': 'Swiss German',
    'bar': 'Bavarian',
    'ksh': 'Colognian',
    'pfl': 'Palatine German',
    'swg': 'Swabian German',
    'wae': 'Walser German',
    'grc': 'Ancient Greek',
    'la': 'Latin',
    'sa': 'Sanskrit',
    'pal': 'Pahlavi',
    'ae': 'Avestan',
    'peo': 'Old Persian',
    'xpr': 'Parthian',
    'xpc': 'Pecheneg',
    'xpg': 'Ancient Greek',
    'xpi': 'Pictish',
    'xpk': 'Kulina',
    'xpl': 'Port Sorell',
    'xpm': 'Pumpokol',
    'xpn': 'Kapinawá',
    'xpo': 'Pochutec',
    'xpp': 'Puyo-Paekche',
    'xpq': 'Mohegan-Pequot',
    'xps': 'Pisidian',
    'xpt': 'Pataxó Hã-Ha-Hãe',
    'xpu': 'Punic',
    'xpv': 'Pamigua',
    'xpw': 'Tupi',
    'xpx': 'Pareci',
    'xpy': 'Puyo',
    'xpz': 'Puelche',
    'xqa': 'Karakhanid',
    'xqt': 'Qatabanian',
    'xra': 'Rarotongan',
    'xrb': 'Eastern Karaboro',
    'xrd': 'Gundungurra',
    'xre': 'Kreye',
    'xrg': 'Minang',
    'xri': 'Krikati-Timbira',
    'xrm': 'Armazic',
    'xrn': 'Arin',
    'xrr': 'Raetic',
    'xrt': 'Aranama-Tamique',
    'xru': 'Marriammu',
    'xrw': 'Karawa',
    'xsa': 'Sabaean',
    'xsb': 'Sambal',
    'xsc': 'Scythian',
    'xsd': 'Sidetic',
    'xse': 'Sempan',
    'xsh': 'Shamang',
    'xsi': 'Sio',
    'xsm': 'Kasem',
    'xsn': 'Sanga',
    'xso': 'Solano',
    'xsp': 'Silopi',
    'xsq': 'Makhuwa-Saaka',
    'xsr': 'Sherpa',
    'xss': 'Assan',
    'xsu': 'Sanumá',
    'xsv': 'Sudovian',
    'xsy': 'Saisiyat',
    'xta': 'Alcozauca Mixtec',
    'xtb': 'Chazumba Mixtec',
    'xtc': 'Katcha-Kadugli-Miri',
    'xtd': 'Diuxi-Tilantongo Mixtec',
    'xte': 'Ketengban',
    'xtg': 'Transalpine Gaulish',
    'xti': 'Sinicahua Mixtec',
    'xtj': 'San Juan Teita Mixtec',
    'xtl': 'Tijaltepec Mixtec',
    'xtm': 'Magdalena Peñasco Mixtec',
    'xtn': 'Northern Tlaxiaco Mixtec',
    'xto': 'Tokharian A',
    'xtp': 'San Miguel Piedras Mixtec',
    'xtq': 'Tumshuqese',
    'xtr': 'Early Tripuri',
    'xts': 'Sindihui Mixtec',
    'xtt': 'Tacahua Mixtec',
    'xtu': 'Cuyamecalco Mixtec',
    'xtv': 'Thawa',
    'xtw': 'Tawandê',
    'xty': 'Yoloxochitl Mixtec',
    'xtz': 'Tasmanian',
    'xua': 'Alu Kurumba',
    'xub': 'Betta Kurumba',
    'xud': 'Umiida',
    'xug': 'Kunigami',
    'xuj': 'Jennu Kurumba',
    'xul': 'Ngunawal',
    'xum': 'Umbrian',
    'xun': 'Unggaranggu',
    'xur': 'Urartian',
    'xuu': 'Kxoe',
    'xve': 'Venetic',
    'xvi': 'Kamviri',
    'xvn': 'Vandalic',
    'xvo': 'Volscian',
    'xvs': 'Vestinian',
    'xwa': 'Kwaza',
    'xwc': 'Woccon',
    'xwd': 'Wadi Wadi',
    'xwe': 'Xwela Gbe',
    'xwg': 'Kwegu',
    'xwl': 'Western Gbe',
    'xwo': 'Written Oirat',
    'xwr': 'Kwerba Mamberamo',
    'xwt': 'Wotjobaluk',
    'xww': 'Wemba Wemba',
    'xxb': 'Boro (Ghana)',
    'xxk': 'Keo',
    'xxm': 'Minkin',
    'xxr': 'Koro (Brazil)',
    'xxt': 'Tambora',
    'xya': 'Yaygir',
    'xyb': 'Yandjibara',
    'xyj': 'Mayi-Yapi',
    'xyl': 'Yalakalore',
    'xyt': 'Mayi-Thakurti',
    'xyy': 'Yorta Yorta',
    'xzh': 'Zhang-Zhung',
    'xzm': 'Zemgalian',
    'xzp': 'Ancient Zapotec',
    'yaa': 'Yaminahua',
    'yab': 'Yuhup',
    'yac': 'Pass Valley Yali',
    'yad': 'Yagua',
    'yae': 'Pumé',
    'yaf': 'Yaka (Democratic Republic of Congo)',
    'yag': 'Yámana',
    'yah': 'Yazgulyam',
    'yai': 'Yagnobi',
    'yaj': 'Banda-Yangere',
    'yak': 'Yakama',
    'yal': 'Yalunka',
    'yam': 'Yamba',
    'yan': 'Mayangna',
    'yao': 'Yao',
    'yap': 'Yapese',
    'yaq': 'Yaqui',
    'yas': 'Nugunu (Cameroon)',
    'yat': 'Yambeta',
    'yau': 'Yuwana',
    'yav': 'Yangben',
    'yaw': 'Yawalapití',
    'yax': 'Yauma',
    'yay': 'Agwagwune',
    'yaz': 'Lokaa',
    'yba': 'Yala',
    'ybb': 'Yemba',
    'ybd': 'Yangbye',
    'ybe': 'West Yugur',
    'ybh': 'Yakha',
    'ybi': 'Yamphu',
    'ybj': 'Hasha',
    'ybk': 'Bokha',
    'ybl': 'Yukuben',
    'ybm': 'Yaben',
    'ybn': 'Yabaâna',
    'ybo': 'Yabong',
    'ybx': 'Yawiyo',
    'yby': 'Yaweyuha',
    'ych': 'Chesu',
    'ycl': 'Lolopo',
    'ycn': 'Yucuna',
    'ycp': 'Chepya',
    'ycr': 'Yilan Creole',
    'ycs': 'Yucatec Maya Sign Language',
    'yct': 'Yucatec Maya',
    'ycu': 'Yuchi',
    'ycv': 'Yulu',
    'ycw': 'Yuchi',
    'ycy': 'Yidgha',
    'yda': 'Yanda',
    'ydd': 'Eastern Yiddish',
    'yde': 'Yangum Dey',
    'ydg': 'Yidgha',
    'ydk': 'Yoidik',
    'yds': 'Yiddish Sign Language',
    'yea': 'Ravula',
    'yec': 'Yeniche',
    'yee': 'Yimas',
    'yei': 'Yeni',
    'yej': 'Yevanic',
    'yes': 'Yeskwa',
    'yet': 'Yetfa',
    'yeu': 'Yerukula',
    'yev': 'Yapunda',
    'yey': 'Yeyi',
    'yga': 'Malyangapa',
    'ygi': 'Yiningayi',
    'ygl': 'Yangum Gel',
    'ygm': 'Yagomi',
    'ygp': 'Gepo',
    'ygr': 'Yagaria',
    'ygs': 'Yolngu Sign Language',
    'ygu': 'Yugul',
    'ygw': 'Yagwoia',
    'yha': 'Baha Buyang',
    'yhd': 'Judeo-Iraqi Arabic',
    'yhl': 'Hlepho Phowa',
    'yhs': 'Yan-nhaŋu Sign Language',
    'yia': 'Yinggarda',
    'yif': 'Ache',
    'yig': 'Wusa Nasu',
    'yih': 'Western Yiddish',
    'yii': 'Yidiny',
    'yij': 'Yindjibarndi',
    'yik': 'Dongshanba Lalo',
    'yil': 'Yindjilandji',
    'yim': 'Yimchungru Naga',
    'yin': 'Yinchia',
    'yip': 'Pholo',
    'yiq': 'Miqie',
    'yir': 'North Awyu',
    'yis': 'Yis',
    'yit': 'Eastern Lalu',
    'yiu': 'Awu',
    'yiv': 'Northern Nisu',
    'yix': 'Axi Yi',
    'yiz': 'Azhe',
    'yka': 'Yakan',
    'ykg': 'Northern Yukaghir',
    'yki': 'Yoke',
    'ykk': 'Yakaikeke',
    'ykl': 'Khlula',
    'ykm': 'Kap',
    'ykn': 'Kua-nsi',
    'yko': 'Yasa',
    'ykr': 'Yugur',
    'ykt': 'Kathu',
    'yku': 'Kuamasi',
    'yky': 'Yakoma',
    'yla': 'Yaul',
    'ylb': 'Yaleba',
    'yle': 'Yele',
    'ylg': 'Yelogu',
    'yli': 'Angguruk Yali',
    'yll': 'Yil',
    'ylm': 'Limi',
    'ylo': 'Naluo Yi',
    'ylr': 'Yalarnnga',
    'ylu': 'Aribwaung',
    'yly': 'Nyâlayu',
    'yma': 'Yamphe',
    'ymb': 'Yambes',
    'ymc': 'Southern Muji',
    'ymd': 'Muda',
    'yme': 'Yameo',
    'ymg': 'Yamongeri',
    'ymh': 'Mili',
    'ymi': 'Moji',
    'ymk': 'Makwe',
    'yml': 'Iamalele',
    'ymm': 'Maay',
    'ymn': 'Yamna',
    'ymo': 'Yangum Mon',
    'ymp': 'Yamap',
    'ymq': 'Qila Muji',
    'ymr': 'Malasar',
    'yms': 'Mysian',
    'ymt': 'Mator-Taygi-Karagas',
    'ymx': 'Northern Muji',
    'ymz': 'Muzi',
    'yna': 'Aluo',
    'ynd': 'Yandruwandha',
    'yne': 'Lang\'e',
    'yng': 'Yango',
    'ynk': 'Naukan Yupik',
    'ynl': 'Yangulam',
    'ynn': 'Yana',
    'yno': 'Yong',
    'ynq': 'Yendang',
    'yns': 'Yansi',
    'ynu': 'Yahuna',
    'yob': 'Yoba',
    'yog': 'Yogad',
    'yoi': 'Yonaguni',
    'yok': 'Yokuts',
    'yom': 'Yombe',
    'yon': 'Yongkom',
    'yor': 'Yoruba',
    'yot': 'Yotti',
    'yox': 'Yoron',
    'yoy': 'Yoy',
    'ypa': 'Phala',
    'ypb': 'Labo Phowa',
    'ypg': 'Phola',
    'yph': 'Phupha',
    'ypk': 'Yupik languages',
    'ypm': 'Phuma',
    'ypn': 'Ano',
    'ypo': 'Phola',
    'ypp': 'Phupa',
    'ypz': 'Phuza',
    'yra': 'Yerakai',
    'yrb': 'Yareba',
    'yre': 'Yaouré',
    'yri': 'Yarí',
    'yrk': 'Nenets',
    'yrl': 'Nhengatu',
    'yrm': 'Yirrk-Mel',
    'yrn': 'Yerong',
    'yro': 'Yaroamë',
    'yrs': 'Yarsun',
    'yrw': 'Yarawata',
    'yry': 'Yarluyandi',
    'ysc': 'Yassic',
    'ysd': 'Samatao',
    'ysg': 'Sonaga',
    'ysl': 'Yugoslavian Sign Language',
    'ysn': 'Sani',
    'yso': 'Nisi (China)',
    'ysp': 'Southern Lolopo',
    'ysr': 'Sirenik Yupik',
    'yss': 'Yessan-Mayo',
    'ysy': 'Sanie',
    'yta': 'Talu',
    'ytl': 'Tanglang',
    'ytp': 'Thopho',
    'ytw': 'Yout Wam',
    'yty': 'Yatay',
    'yua': 'Yucatec Maya',
    'yub': 'Yugambal',
    'yuc': 'Yuchi',
    'yud': 'Judeo-Tripolitanian Arabic',
    'yue': 'Yue Chinese',
    'yuf': 'Havasupai-Walapai-Yavapai',
    'yug': 'Yug',
    'yui': 'Yurutí',
    'yuj': 'Karkar-Yuri',
    'yuk': 'Yuki',
    'yul': 'Yulu',
    'yum': 'Quechan',
    'yun': 'Bena (Nigeria)',
    'yup': 'Yukpa',
    'yuq': 'Yuqui',
    'yur': 'Yurok',
    'yut': 'Yopno',
    'yuu': 'Yugh',
    'yuw': 'Yau (Morobe Province)',
    'yux': 'Southern Yukaghir',
    'yuy': 'East Yugur',
    'yuz': 'Yuracare',
    'yva': 'Yawa',
    'yvt': 'Yavitero',
    'ywa': 'Kalou',
    'ywg': 'Yindjilandji',
    'ywl': 'Western Lalu',
    'ywn': 'Yawanawa',
    'ywq': 'Wuding-Luquan Yi',
    'ywr': 'Yawuru',
    'ywt': 'Xishanba Lalo',
    'ywu': 'Wumeng Nasu',
    'yww': 'Yawarawarga',
    'yxa': 'Mayawali',
    'yxg': 'Yagara',
    'yxl': 'Yardliyawarra',
    'yxm': 'Yinwum',
    'yxu': 'Yuyu',
    'yxy': 'Yabula Yabula',
    'yyr': 'Yir Yoront',
    'yyu': 'Yau (Sandaun Province)',
    'yyz': 'Ayizi',
    'yzg': 'E\'ma Buyang',
    'yzk': 'Zokhuo',
    'zaa': 'Sierra de Juárez Zapotec',
    'zab': 'Western Tlacolula Valley Zapotec',
    'zac': 'Ocotlán Zapotec',
    'zad': 'Cajonos Zapotec',
    'zae': 'Yareni Zapotec',
    'zaf': 'Ayoquesco Zapotec',
    'zag': 'Zaghawa',
    'zah': 'Zangwal',
    'zai': 'Isthmus Zapotec',
    'zaj': 'Zaramo',
    'zak': 'Zanaki',
    'zal': 'Zauzou',
    'zam': 'Miahuatlán Zapotec',
    'zao': 'Ozolotepec Zapotec',
    'zap': 'Zapotec',
    'zaq': 'Aloápam Zapotec',
    'zar': 'Rincón Zapotec',
    'zas': 'Santo Domingo Albarradas Zapotec',
    'zat': 'Tabaa Zapotec',
    'zau': 'Zangskari',
    'zav': 'Yatzachi Zapotec',
    'zaw': 'Mitla Zapotec',
    'zax': 'Xadani Zapotec',
    'zay': 'Zayse-Zergulla',
    'zaz': 'Zari',
    'zbc': 'Central Berawan',
    'zbe': 'East Berawan',
    'zbl': 'Blissymbols',
    'zbt': 'Batui',
    'zbu': 'Bu (Bauchi State)',
    'zbw': 'West Berawan',
    'zca': 'Coatecas Altas Zapotec',
    'zch': 'Central Hongshuihe Zhuang',
    'zdj': 'Ngazidja Comorian',
    'zea': 'Zeeuws',
    'zeg': 'Zenag',
    'zeh': 'Eastern Hongshuihe Zhuang',
    'zen': 'Zenaga',
    'zga': 'Kinga',
    'zgb': 'Guibei Zhuang',
    'zgh': 'Standard Moroccan Tamazight',
    'zgm': 'Minz Zhuang',
    'zgn': 'Guibian Zhuang',
    'zgr': 'Magori',
    'zhb': 'Zhaba',
    'zhd': 'Dai Zhuang',
    'zhi': 'Zhire',
    'zhn': 'Nong Zhuang',
    'zho': 'Chinese',
    'zhw': 'Zhoa',
    'zia': 'Zia',
    'zib': 'Zimbabwe Sign Language',
    'zik': 'Zimakani',
    'zil': 'Zialo',
    'zim': 'Mesme',
    'zin': 'Zinza',
    'zir': 'Ziriya',
    'ziw': 'Zigula',
    'ziz': 'Zizilivakan',
    'zka': 'Kaimbulawa',
    'zkb': 'Koibal',
    'zkd': 'Kadu',
    'zkg': 'Koguryo',
    'zkh': 'Khorezmian',
    'zkk': 'Karankawa',
    'zkn': 'Kanan',
    'zko': 'Kott',
    'zkp': 'São Paulo Kaingáng',
    'zkr': 'Zakhring',
    'zkt': 'Kitan',
    'zku': 'Kaurna',
    'zkv': 'Krevinian',
    'zkz': 'Khazar',
    'zlj': 'Liujiang Zhuang',
    'zlm': 'Malay (individual language)',
    'zln': 'Lianshan Zhuang',
    'zlq': 'Liuqian Zhuang',
    'zma': 'Manda (Australia)',
    'zmb': 'Zimba',
    'zmd': 'Maridan',
    'zmg': 'Marti Ke',
    'zmi': 'Negeri Sembilan Malay',
    'zml': 'Madngele',
    'zmm': 'Marimanindji',
    'zmn': 'Mbangwe',
    'zmo': 'Molo',
    'zmp': 'Mpuono',
    'zmq': 'Mituku',
    'zmr': 'Maranunggu',
    'zms': 'Mbesa',
    'zmt': 'Maringarr',
    'zmu': 'Muruwari',
    'zmv': 'Mbariman-Gudhinma',
    'zmw': 'Mbo (Democratic Republic of Congo)',
    'zmx': 'Bomitaba',
    'zmy': 'Mariyedi',
    'zmz': 'Mbandja',
    'zna': 'Zan Gula',
    'znd': 'Zande languages',
    'zne': 'Zande (individual language)',
    'zng': 'Mang',
    'znk': 'Manangkari',
    'zns': 'Mangas',
    'zoc': 'Copainalá Zoque',
    'zoh': 'Chimalapa Zoque',
    'zom': 'Zou',
    'zoo': 'Asunción Mixtepec Zapotec',
    'zoq': 'Tabasco Zoque',
    'zor': 'Rayón Zoque',
    'zos': 'Francisco León Zoque',
    'zpa': 'Lachiguiri Zapotec',
    'zpb': 'Yautepec Zapotec',
    'zpc': 'Choapan Zapotec',
    'zpd': 'Southeastern Ixtlán Zapotec',
    'zpe': 'Petapa Zapotec',
    'zpf': 'San Pedro Quiatoni Zapotec',
    'zpg': 'Guevea De Humboldt Zapotec',
    'zph': 'Totomachapan Zapotec',
    'zpi': 'Santa María Quiegolani Zapotec',
    'zpj': 'Quiavicuzas Zapotec',
    'zpk': 'Tlacolulita Zapotec',
    'zpl': 'Lachixío Zapotec',
    'zpm': 'Mixtepec Zapotec',
    'zpn': 'Santa Inés Yatzechi Zapotec',
    'zpo': 'Amatlán Zapotec',
    'zpp': 'El Alto Zapotec',
    'zpq': 'Zoogocho Zapotec',
    'zpr': 'Santiago Xanica Zapotec',
    'zps': 'Coatlán Zapotec',
    'zpt': 'San Vicente Coatlán Zapotec',
    'zpu': 'Yalálag Zapotec',
    'zpv': 'Chichicapan Zapotec',
    'zpw': 'Zaniza Zapotec',
    'zpx': 'San Baltazar Loxicha Zapotec',
    'zpy': 'Mazaltepec Zapotec',
    'zpz': 'Tlacochahuaya Zapotec',
    'zqe': 'Qiubei Zhuang',
    'zra': 'Kara (Korea)',
    'zrg': 'Mirgan',
    'zrn': 'Zerenkel',
    'zro': 'Záparo',
    'zrp': 'Zarphatic',
    'zrs': 'Mairasi',
    'zsa': 'Sarasira',
    'zsk': 'Kaskean',
    'zsl': 'Zambian Sign Language',
    'zsm': 'Standard Malay',
    'zsr': 'Southern Rincon Zapotec',
    'zsu': 'Sukurum',
    'zte': 'Elotepec Zapotec',
    'ztg': 'Xanaguía Zapotec',
    'ztl': 'Lapaguía-Guivini Zapotec',
    'ztm': 'San Agustín Mixtepec Zapotec',
    'ztn': 'Santa Catarina Albarradas Zapotec',
    'ztp': 'Loxicha Zapotec',
    'ztq': 'Quioquitani-Quierí Zapotec',
    'zts': 'Tilquiapan Zapotec',
    'ztt': 'Tejalapan Zapotec',
    'ztu': 'Güilá Zapotec',
    'ztx': 'Zaachila Zapotec',
    'zty': 'Yatee Zapotec',
    'zua': 'Zeem',
    'zuh': 'Tokano',
    'zul': 'Zulu',
    'zum': 'Kumzari',
    'zun': 'Zuni',
    'zuy': 'Zumaya',
    'zwa': 'Zay',
    'zxx': 'No linguistic content',
    'zyb': 'Yongbei Zhuang',
    'zyg': 'Yang Zhuang',
    'zyj': 'Youjiang Zhuang',
    'zyn': 'Yongnan Zhuang',
    'zyp': 'Zyphe Chin',
    'zza': 'Zaza',
    'zzj': 'Zuojiang Zhuang'
  };
  
  return languageMap[code] || code;
}; 